pages_adminPages:
    resource: "@PagesBundle/Resources/config/routing/routingAdmin.yml"
    prefix:   /admin/pages

page:
    path: /page/{slug}
    defaults: { _controller: PagesBundle:Pages1:page }
