routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /

routingProduitsAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduitsAdmin.yml"
    prefix: /admin/produits

routingCategoriesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCategories.yml"
    prefix:   /admin/categories

routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /

routingCommandesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
    prefix: /admin/commandes

routingAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingAdmin.yml"
    prefix: /admin