<?php
/**
 * Created by PhpStorm.
 * User: cedric
 * Date: 04/04/2017
 * Time: 16:46
 */

namespace EcommerceBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use UtilisateursBundle\Entity\Utilisateurs;

class TestType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options){
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

    $builder->add('email', EmailType::class ,array('required' => false) )
    ->add('nom')
    ->add('utilisateurs', EntityType::class, array('class' => 'UtilisateursBundle:Utilisateurs'))
    ->add('Villes', CountryType::class)
    ->add('sexe', ChoiceType::class, array(
        'choices'  => array(
            '0' => 'homme',
            '1' => 'femme',
            '2' => 'trans',
        )))
    ->add('contenu')
    ->add('date', DateType::class)
    ->add('envoyer', SubmitType::class);
    }

    public function getName(){
        return 'ecommerce_ecommercebundle_test';
    }



}